version: 1.0  # work in progress

description: A workflow consists of reading Slack message  ,send an email and respond back to slack

input:
  - slack_message: null  # Input parameter to receive the Slack message

tasks:
  task1:
    action: slack_dilshan.send_email
    next:
      - when: <% succeeded() %>
        publish: greeting=<% result().stdout %>
        do: task2
  task2:
    action: slack_dilshan.send_message_to_slack
    input:
      message: "All your base are belong to us!"
    next:
      - when: <% succeeded() %>
        publish:
          - greeting: <% ctx("greeting") %>, <% result().stdout %>
 
  