name: "slack_respond_to_email_send"
pack: "slack_dilshan"
description: "This rule scans the Slack for email send instructions ,send an email and respond back to channel"
enabled: true 
trigger:
  type: "slack.message"
# criteria:
#   trigger.text:
#     type: "contains"
#     pattern: "email"
action:
  ref: "slack_dilshan.send_message"
  parameters:
    user: "{{trigger.user.name}}"
    text: "{{trigger.text}}"
    channel: "{{trigger.channel.name}}"
    timestamp: "{{trigger.timestamp_raw}}"