name: "slack_respond_to_email_send"
pack: "slack_dilshan"
description: "This rule scans the Slack for email send instructions, sends an email, and responds back to the channel"
enabled: true
trigger:
  type: "slack_dilshan.new_update"
  parameters: {}
criteria:
  trigger.text:
    type: "contains"
    pattern: "email"
action:
  ref: core.local
  parameters:
    cmd: "echo trigger" 
    #cmd: "echo {{ trigger.message.attributes[0].attributeName }}: {{ trigger.message.attributes[0].attributeValue }}"
 
