name: "slack_respond_to_email_send"
pack: "slack_dilshan"
description: "This rule scans the Slack for email send instructions ,send an email and respond back to channel"
enabled: true 
trigger:
  type: "slack_dilshan.new_update"
  parameters: {}
criteria:
  trigger.receiver_email:
    type: "contains"
    pattern: "gmail"
#criteria: {}   #if we want empty criteria...no rule matching  
action:
  #ref: "slack_dilshan.send_message"
  ref: "slack_dilshan.sequential_slack"
  parameters:
    #text: "{{trigger.text}}"
    receiver_email: "{{trigger.receiver_email}}"
    receiver_whatsapp_number: "{{trigger.receiver_whatsapp_number}}"
    receiver_sms: "{{trigger.receiver_sms}}"

  
